/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "nor1.v:1.1-3.10" *)
module nor1(a, b, y);
  (* src = "nor1.v:1.19-1.20" *)
  input a;
  wire a;
  (* src = "nor1.v:1.28-1.29" *)
  input b;
  wire b;
  (* src = "nor1.v:1.38-1.39" *)
  output y;
  wire y;
  assign y = ~(b ^ a);
endmodule
